/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Karolina Renkiewicz (https://sketchfab.com/KarolinaRenkiewicz)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/bitcoin-ff17dab54b044d789d05ae7c8dfb9808
title: Bitcoin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bitcoin({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bitcoin.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-3.49, 36.23, -11.29]}>
            <mesh geometry={nodes.Cylinder002__0.geometry} material={materials['Scene_-_Root']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bitcoin.glb')
