/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: arthur (https://sketchfab.com/Arthur_mf)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/bitcoin-974eb93e7e1346e8a18086b4e6529703
title: Bitcoin
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Bitcointhree({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bitcointhree.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group  position={[0, -0.45, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
          </group>
          <group position={[0, -0.45, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials['Material.002']} />
          </group>
          <group  position={[0, -0.45, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={2.41}>
            <mesh geometry={nodes.Object_9.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Object_10.geometry} material={materials['Material.003']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bitcointhree.glb')
