/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: vintnes6 (https://sketchfab.com/vintnes6)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cypher-valorant-e59de758479d4f5c8714183e94a4d047
title: Cypher [Valorant]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Cypher({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/cypher.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[0, -0.45, 0]}>
      <group position={[0, -0.45, 0]}rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[-Math.PI, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.TP_Gumshoe_S0_MI} skeleton={nodes.Object_6.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cypher.glb')