/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

function Fredbear({ ...props }) {
	const group = useRef();
	const { nodes, materials } = useGLTF('/fredbear.glb');
	console.log(nodes, 'nodes');
	return (
		<group ref={group} {...props} dispose={null}>
			<group position={[0, -0.45, -0.02]} rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					geometry={nodes.mesh_0.geometry}
					material={nodes.mesh_0.material}
				/>
				<mesh
					geometry={nodes.mesh_0_1.geometry}
					material={nodes.mesh_0_1.material}
				/>
			</group>
			<mesh
				geometry={nodes.mesh_1.geometry}
				material={nodes.mesh_1.material}
				position={[0, -0.45, -0.02]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.mesh_2.geometry}
				material={nodes.mesh_2.material}
				position={[0, -0.45, -0.02]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.mesh_3.geometry}
				material={nodes.mesh_3.material}
				position={[0, -0.45, -0.02]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.mesh_4.geometry}
				material={nodes.mesh_4.material}
				position={[0, -0.45, -0.02]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
			<mesh
				geometry={nodes.mesh_5.geometry}
				material={nodes.mesh_5.material}
				position={[0, -0.45, -0.02]}
				rotation={[-Math.PI / 2, 0, 0]}
			/>
		</group>
	);
}

export default Fredbear;

useGLTF.preload('/fredbear.glb');
