/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: vintnes6 (https://sketchfab.com/vintnes6)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/new-omen-model-valorant-e3173934d98140aebfaec2aaeeb07350
title: New Omen Model [Valorant]
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Game({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/game.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[0, 0, -0.2]}>
      <group position={[0, -202.5, 0.2]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[-Math.PI, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.TP_Wraith_V5_S0_MI} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.TP_Wraith_Head_S0_MI} skeleton={nodes.Object_8.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/game.glb')
