/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Gianmarco (https://sketchfab.com/GianmArt)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/squid-game-guards-148201371444413d9545409c4714271a
title: Squid game - guards
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Gaurdsglb({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gaurdsglb.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[0, -0.45, -0.02]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 130.33, 5.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube002_maschera_cerchio_0.geometry} material={materials.maschera_cerchio} />
          </group>
          <group position={[0, 121.4, -2.56]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.chest003_tuta_0.geometry} material={materials.tuta} />
            <mesh geometry={nodes.chest003_Material008_0.geometry} material={materials['Material.008']} />
          </group>
          <group position={[0, 122.03, -2.74]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.chest001_tuta_0.geometry} material={materials.tuta} />
          </group>
          <group position={[0.04, 7.17, 8.93]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube011_scarpe_0.geometry} material={materials.scarpe} />
          </group>
          <group position={[9.62, 3.33, 8.03]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube005_scarpe_0.geometry} material={materials.scarpe} />
          </group>
          <group position={[10.02, 8.41, 21.1]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.NurbsCurve001_scarpe3_0.geometry} material={materials.scarpe3} />
          </group>
          <group position={[0, 132.69, 4.26]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube018_guanti_0.geometry} material={materials.guanti} />
          </group>
          <group position={[0, 67.86, -0.77]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.chest002_Material012_0.geometry} material={materials['Material.012']} />
          </group>
          <group position={[0, 130.33, 5.2]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube008_mask2_0.geometry} material={materials.mask2} />
            <mesh geometry={nodes.Cube008_mask3_0.geometry} material={materials.mask3} />
          </group>
          <group position={[-8.57, 64.65, 10.34]} rotation={[-0.14, -0.35, -0.22]} scale={100}>
            <mesh geometry={nodes.chest005_tuta_0.geometry} material={materials.tuta} />
          </group>
          <group position={[-8.57, 64.65, 10.34]} rotation={[-0.14, -0.35, -0.22]} scale={100}>
            <mesh geometry={nodes.chest006_tuta_0.geometry} material={materials.tuta} />
          </group>
          <group position={[0, 131.72, 2.38]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube006_Material011_0.geometry} material={materials['Material.011']} />
          </group>
          <group position={[1.2, 66.53, 10.6]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Cube_Material003_0.geometry} material={materials['Material.003']} />
          </group>
          <group position={[8.08, 90.22, 10.88]} rotation={[-Math.PI / 2, 0, 0.04]} scale={103.68}>
            <mesh geometry={nodes.chest018_tuta_0.geometry} material={materials.tuta} />
          </group>
          <group position={[17.64, 47.48, 0.51]} rotation={[-Math.PI / 2, -0.05, 1.31]} scale={140.08}>
            <mesh geometry={nodes.chest019_tuta_0.geometry} material={materials.tuta} />
          </group>
          <group position={[50.53, 72.21, -5.05]} rotation={[-1.63, 0.21, 1.56]} scale={9.03}>
            <group position={[0, -2.15, 1.58]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Circle021_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, -3, 1.07]} rotation={[0, 0, Math.PI / 2]} scale={11.08}>
              <mesh geometry={nodes.Cube070_mitra2_0.geometry} material={materials.mitra2} />
            </group>
            <group position={[0, -2.06, 1.25]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Circle022_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]}>
              <mesh geometry={nodes.Cube071_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, -2.15, 1.58]} rotation={[Math.PI / 2, 0, 0]} scale={11.08}>
              <mesh geometry={nodes.Circle023_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]}>
              <mesh geometry={nodes.Cube072_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]}>
              <mesh geometry={nodes.Cube073_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.19]}>
              <mesh geometry={nodes.Cube074_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, -2.06, 1.27]}>
              <mesh geometry={nodes.Circle024_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]}>
              <mesh geometry={nodes.Cube076_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, -3, 1.07]} rotation={[0, 0, Math.PI / 2]}>
              <mesh geometry={nodes.Cube077_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]}>
              <mesh geometry={nodes.Cube078_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]}>
              <mesh geometry={nodes.Cube079_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0.19, -0.46, 0.78]} rotation={[-2.77, 0, 0]} scale={0.06}>
              <mesh geometry={nodes.Cube080_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]} scale={11.08}>
              <mesh geometry={nodes.Cube081_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, -2.06, 1.27]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes.Circle025_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.17]} scale={11.08}>
              <mesh geometry={nodes.Cube082_mitra_0.geometry} material={materials.mitra} />
            </group>
            <group position={[0, 0.34, 1.19]} scale={11.08}>
              <mesh geometry={nodes.Cube083_mitra2_0.geometry} material={materials.mitra2} />
            </group>
            <mesh geometry={nodes.Cube075_mitra_0.geometry} material={materials.mitra} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint} />
            <group position={[0, -0.05, 1.3]}>
              <mesh geometry={nodes.Cube001_maschera_triangolo_0.geometry} material={materials.maschera_triangolo} />
            </group>
            <group position={[0, 0.03, 1.21]}>
              <mesh geometry={nodes.chest008_tuta_0.geometry} material={materials.tuta} />
              <mesh geometry={nodes.chest008_Material008_0.geometry} material={materials['Material.008']} />
            </group>
            <group position={[0, 0.03, 1.22]}>
              <mesh geometry={nodes.chest009_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[0, -0.09, 0.07]}>
              <mesh geometry={nodes.Cube003_scarpe_0.geometry} material={materials.scarpe} />
            </group>
            <group position={[0.1, -0.08, 0.03]}>
              <mesh geometry={nodes.Cube004_scarpe_0.geometry} material={materials.scarpe} />
            </group>
            <group position={[0.1, -0.21, 0.08]}>
              <mesh geometry={nodes.NurbsCurve002_scarpe3_0.geometry} material={materials.scarpe3} />
            </group>
            <group position={[0, -0.04, 1.33]}>
              <mesh geometry={nodes.Cube007_guanti_0.geometry} material={materials.guanti} />
            </group>
            <group position={[0, 0.01, 0.68]}>
              <mesh geometry={nodes.chest010_Material012_0.geometry} material={materials['Material.012']} />
            </group>
            <group position={[0, -0.05, 1.3]}>
              <mesh geometry={nodes.Cube009_mask2_0.geometry} material={materials.mask2} />
              <mesh geometry={nodes.Cube009_mask3_0.geometry} material={materials.mask3} />
            </group>
            <group position={[-0.09, -0.1, 0.65]} rotation={[1.43, -0.35, -0.22]}>
              <mesh geometry={nodes.chest011_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[-0.09, -0.1, 0.65]} rotation={[1.43, -0.35, -0.22]}>
              <mesh geometry={nodes.chest012_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[0, -0.02, 1.32]}>
              <mesh geometry={nodes.Cube010_Material011_0.geometry} material={materials['Material.011']} />
            </group>
            <group position={[0.01, -0.11, 0.67]}>
              <mesh geometry={nodes.Cube012_Material003_0.geometry} material={materials['Material.003']} />
            </group>
            <group position={[0.08, -0.11, 0.9]} rotation={[0, 0, 0.04]} scale={1.04}>
              <mesh geometry={nodes.chest013_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[0.18, -0.01, 0.47]} rotation={[0, -0.05, 1.31]} scale={1.4}>
              <mesh geometry={nodes.chest014_tuta_0.geometry} material={materials.tuta} />
            </group>
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes._rootJoint_1} />
            <group position={[0, -0.05, 1.3]}>
              <mesh geometry={nodes.Cube029_maschera_quadrato_0.geometry} material={materials.maschera_quadrato} />
            </group>
            <group position={[0, 0.03, 1.21]}>
              <mesh geometry={nodes.chest015_tuta_0.geometry} material={materials.tuta} />
              <mesh geometry={nodes.chest015_Material008_0.geometry} material={materials['Material.008']} />
            </group>
            <group position={[0, 0.03, 1.22]}>
              <mesh geometry={nodes.chest016_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[0, -0.09, 0.07]}>
              <mesh geometry={nodes.Cube030_scarpe_0.geometry} material={materials.scarpe} />
            </group>
            <group position={[0.1, -0.08, 0.03]}>
              <mesh geometry={nodes.Cube031_scarpe_0.geometry} material={materials.scarpe} />
            </group>
            <group position={[0.1, -0.21, 0.08]}>
              <mesh geometry={nodes.NurbsCurve003_scarpe3_0.geometry} material={materials.scarpe3} />
            </group>
            <group position={[0, -0.04, 1.33]}>
              <mesh geometry={nodes.Cube032_guanti_0.geometry} material={materials.guanti} />
            </group>
            <group position={[0, 0.01, 0.68]}>
              <mesh geometry={nodes.chest017_Material012_0.geometry} material={materials['Material.012']} />
            </group>
            <group position={[0, -0.05, 1.3]}>
              <mesh geometry={nodes.Cube033_mask2_0.geometry} material={materials.mask2} />
              <mesh geometry={nodes.Cube033_mask3_0.geometry} material={materials.mask3} />
            </group>
            <group position={[-0.09, -0.1, 0.65]} rotation={[1.43, -0.35, -0.22]}>
              <mesh geometry={nodes.chest027_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[-0.09, -0.1, 0.65]} rotation={[1.43, -0.35, -0.22]}>
              <mesh geometry={nodes.chest028_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[0, -0.02, 1.32]}>
              <mesh geometry={nodes.Cube034_Material011_0.geometry} material={materials['Material.011']} />
            </group>
            <group position={[0.01, -0.11, 0.67]}>
              <mesh geometry={nodes.Cube035_Material003_0.geometry} material={materials['Material.003']} />
            </group>
            <group position={[0.08, -0.11, 0.9]} rotation={[0, 0, 0.04]} scale={1.04}>
              <mesh geometry={nodes.chest029_tuta_0.geometry} material={materials.tuta} />
            </group>
            <group position={[0.18, -0.01, 0.47]} rotation={[0, -0.05, 1.31]} scale={1.4}>
              <mesh geometry={nodes.chest030_tuta_0.geometry} material={materials.tuta} />
            </group>
          </group>
          <group position={[0, -0.78, 29.07]} rotation={[-Math.PI / 2, 0, 0]} scale={131.48}>
            <group position={[0, 0.74, 0]} scale={1.05}>
              <mesh geometry={nodes.Plane001_Material001_0.geometry} material={materials['Material.001']} />
            </group>
            <group position={[0, -0.34, 0]} scale={[0.45, 0.45, 1]}>
              <mesh geometry={nodes.Circle001_Material001_0.geometry} material={materials['Material.001']} />
            </group>
            <group position={[0, 0.97, 0]} scale={[0.45, 0.45, 0.84]}>
              <mesh geometry={nodes.Circle002_Material001_0.geometry} material={materials['Material.001']} />
            </group>
            <mesh geometry={nodes.Plane002_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[218.33, 218.33, 123.22]}>
            <mesh geometry={nodes.Circle_Material_0.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/gaurdsglb.glb')
