/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function GipsyDange({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/GipsyDange.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes['3MFMeshParent_0'].geometry} material={nodes['3MFMeshParent_0'].material} position={[0, -0.45, -0.02]} scale={0.4} />
    </group>
  )
}

useGLTF.preload('/GipsyDange.glb')
