/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Nontechrobo({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/nontechrobo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.Group29284.geometry} material={materials['default']} />
    </group>
  )
}

useGLTF.preload('/nontechrobo.glb')
