/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Darryl Chooi (https://sketchfab.com/darryl0210)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/roadshow-stage-2022-v3-d728436bd12d47e385ba6ecedb57f754
title: Roadshow Stage 2022 V3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0}>
          <group position={[-29.13, 192.5, 1318.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 5288.16, 4046.48]}>
              <mesh geometry={nodes['Rectangle001_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 286.25, 1193.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 5163.16, 3952.73]}>
              <mesh geometry={nodes['Rectangle001_002_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 380, 1068.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 5038.16, 3858.98]}>
              <mesh geometry={nodes['Rectangle001_003_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 98.75, 1443.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 5413.16, 4140.23]}>
              <mesh geometry={nodes['Rectangle001_004_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[7975.88, 2695.65, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8005.01, 2497.81, 1543.33]}>
              <mesh geometry={nodes['Rectangle001_005_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[12127.87, 2070.49, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-12157, 2497.81, 2168.49]}>
              <mesh geometry={nodes['Rectangle001_006_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[9288.63, 1690.36, -4527.24]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9317.76, -557.49, 2548.62]}>
              <mesh geometry={nodes['Rectangle001_007_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[9667.07, 5023.54, -1827.93]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9696.2, 2141.83, -784.56]}>
              <mesh geometry={nodes['Rectangle001_008_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 3837.96, -9390.79]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -5421.04, 401.02]}>
              <mesh geometry={nodes['Rectangle001_009_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8770.59, 3357.09, -6311.47]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8741.46, -2341.72, 881.89]}>
              <mesh geometry={nodes['Rectangle001_010_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8739.34, 3653.72, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8710.21, -960.72, 585.26]}>
              <mesh geometry={nodes['Rectangle001_011_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8739.34, 3732.85, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8710.21, -960.72, 506.13]}>
              <mesh geometry={nodes['Rectangle001_012_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8739.34, 3809.89, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8710.21, -960.72, 429.09]}>
              <mesh geometry={nodes['Rectangle001_013_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8739.34, 3897.34, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8710.21, -960.72, 341.64]}>
              <mesh geometry={nodes['Rectangle001_014_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8739.34, 3981.08, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8710.21, -960.72, 257.9]}>
              <mesh geometry={nodes['Rectangle001_015_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8034.14, 2695.65, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8005.01, 2497.81, 1543.33]}>
              <mesh geometry={nodes['Rectangle001_016_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-9346.89, 1690.36, -4527.24]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9317.76, -557.49, 2548.62]}>
              <mesh geometry={nodes['Rectangle001_017_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-9725.33, 5023.54, -1827.93]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9696.2, 2141.83, -784.56]}>
              <mesh geometry={nodes['Rectangle001_018_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-12186.13, 2070.49, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[12157, 2497.81, 2168.49]}>
              <mesh geometry={nodes['Rectangle001_019_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8932.08, 3357.09, -6311.47]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8961.21, -2341.72, 881.89]}>
              <mesh geometry={nodes['Rectangle001_020_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8900.83, 3653.72, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8929.96, -960.72, 585.26]}>
              <mesh geometry={nodes['Rectangle001_021_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8900.83, 3732.85, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8929.96, -960.72, 506.13]}>
              <mesh geometry={nodes['Rectangle001_022_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8900.83, 3809.89, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8929.96, -960.72, 429.09]}>
              <mesh geometry={nodes['Rectangle001_023_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8900.83, 3897.34, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8929.96, -960.72, 341.64]}>
              <mesh geometry={nodes['Rectangle001_024_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8900.83, 3981.08, -4930.48]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8929.96, -960.72, 257.9]}>
              <mesh geometry={nodes['Rectangle001_025_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-9346.36, 1423.45, -1929.9]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9317.23, 2039.85, 2815.53]}>
              <mesh geometry={nodes['Object026_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[9760.37, 5020.6, -1921.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9789.5, 3703.31, -1178.47]}>
              <mesh geometry={nodes['Rectangle022_001_Material_#126_0'].geometry} material={materials.Material_126} />
            </group>
          </group>
          <group position={[-29.13, 3842.13, -9328.29]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -3703.31, 0]}>
              <mesh geometry={nodes['Rectangle022_002_Material_#126_0'].geometry} material={materials.Material_126} />
            </group>
          </group>
          <group position={[-9818.63, 5020.6, -1921.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9789.5, 3703.31, -1178.47]}>
              <mesh geometry={nodes['Rectangle022_003_Material_#126_0'].geometry} material={materials.Material_126} />
            </group>
          </group>
          <group position={[-29.13, 3837.96, -9515.79]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Rectangle035_001_Material_#133_0'].geometry} material={materials.Material_133} />
          </group>
          <group position={[-8778.36, 3263.79, -6314.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9166.1, 0, 0]}>
              <mesh geometry={nodes['Rectangle040_001_Material_#131_0'].geometry} material={materials.Material_131} />
            </group>
          </group>
          <group position={[-8758.97, 3263.79, -6314.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9146.7, 0, 0]}>
              <mesh geometry={nodes['Rectangle040_002_Material_#131_0'].geometry} material={materials.Material_131} />
            </group>
          </group>
          <group position={[8939.85, 3263.79, -6314.4]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8552.11, 0, 0]}>
              <mesh geometry={nodes['Rectangle040_003_Material_#131_0'].geometry} material={materials.Material_131} />
            </group>
          </group>
          <group position={[8920.45, 3263.79, -6314.4]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8532.72, 0, 0]}>
              <mesh geometry={nodes['Rectangle040_004_Material_#131_0'].geometry} material={materials.Material_131} />
            </group>
          </group>
          <group position={[-77.98, 8619.31, -9031.79]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes['Object020_013_LOGO-white_0'].geometry} material={materials['LOGO-white']} />
          </group>
          <group position={[-10963.88, 2187.02, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[10934.75, 2497.81, 2051.96]}>
              <mesh geometry={nodes['Object025_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8199.85, 1878.38, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8170.72, 2497.81, 2360.6]}>
              <mesh geometry={nodes['Object025_002_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[10905.63, 2187.02, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-10934.75, 2497.81, 2051.96]}>
              <mesh geometry={nodes['Object025_003_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8141.59, 1878.38, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8170.72, 2497.81, 2360.6]}>
              <mesh geometry={nodes['Object025_004_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 405, -3950.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 19.73, 3833.98]}>
              <mesh geometry={nodes['Object021_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 130, -3845.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 124.73, 4108.98]}>
              <mesh geometry={nodes['Object022_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 3842.13, -9297.04]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -5327.29, 396.85]}>
              <mesh geometry={nodes['Object023_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-29.13, 4239.04, -9811.29]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -5841.54, -0.06]}>
              <mesh geometry={nodes['Object024_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[1.61, 3700.21, -9937.03]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-30.74, -5967.28, 538.77]}>
              <mesh geometry={nodes['Object024_002_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[-8676.84, 3218.16, -4968.11]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8647.71, -998.36, 1020.83]}>
              <mesh geometry={nodes.Mesh001_001_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8676.84, 5766.11, -6203.54]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8647.71, -2233.79, -1527.12]}>
              <mesh geometry={nodes.Mesh001_002_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8739.34, 3307.44, -7662.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8710.21, -3692.39, 931.55]}>
              <mesh geometry={nodes.Mesh001_003_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8838.33, 3218.16, -4968.12]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8867.46, -998.36, 1020.83]}>
              <mesh geometry={nodes.Mesh001_004_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8838.33, 5766.11, -6203.54]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8867.46, -2233.79, -1527.13]}>
              <mesh geometry={nodes.Mesh001_005_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8900.83, 3307.44, -7662.14]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8929.96, -3692.39, 931.55]}>
              <mesh geometry={nodes.Mesh001_006_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9288.1, 1423.46, -1929.9]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9317.23, 2039.85, 2815.53]}>
              <mesh geometry={nodes['Object027_001_Stage-white_0'].geometry} material={materials['Stage-white']} />
            </group>
          </group>
          <group position={[8030.65, 1901.96, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8059.77, 2116.56, 2337.02]}>
              <mesh geometry={nodes.Rectangle011_001_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8590.25, 1065.48, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8619.38, 2116.56, 3173.5]}>
              <mesh geometry={nodes.Rectangle011_002_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8508.28, 1136.46, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8537.41, 2116.56, 3102.52]}>
              <mesh geometry={nodes.Rectangle011_003_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8468.05, 1233.31, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8497.18, 2116.56, 3005.67]}>
              <mesh geometry={nodes.Rectangle011_004_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[11041.7, 2217.44, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-11070.83, 2116.56, 2021.54]}>
              <mesh geometry={nodes.Rectangle011_005_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[11109.68, 2364.44, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-11138.81, 2116.56, 1874.54]}>
              <mesh geometry={nodes.Rectangle011_006_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[11300.34, 2476.26, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-11329.47, 2116.56, 1762.72]}>
              <mesh geometry={nodes.Rectangle011_007_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[11416.96, 2655.45, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-11446.09, 2116.56, 1583.53]}>
              <mesh geometry={nodes.Rectangle011_008_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9806, 6366.89, -1921.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9835.13, 1666.83, -2127.91]}>
              <mesh geometry={nodes.Rectangle011_009_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[7258.05, 5131.47, -1921.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-7287.18, 1666.83, -892.49]}>
              <mesh geometry={nodes.Rectangle011_010_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9716.72, 3672.87, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9745.85, 1729.33, 566.11]}>
              <mesh geometry={nodes.Rectangle011_011_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9370.44, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9399.57, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_012_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9291.31, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9320.44, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_013_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9214.27, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9243.4, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_014_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9126.82, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9155.95, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_015_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9043.08, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9072.21, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_016_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8088.9, 1901.96, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8059.77, 2116.56, 2337.02]}>
              <mesh geometry={nodes.Rectangle011_017_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8648.51, 1065.48, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8619.38, 2116.56, 3173.5]}>
              <mesh geometry={nodes.Rectangle011_018_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8566.54, 1136.46, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8537.41, 2116.56, 3102.52]}>
              <mesh geometry={nodes.Rectangle011_019_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8526.31, 1233.31, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8497.18, 2116.56, 3005.67]}>
              <mesh geometry={nodes.Rectangle011_020_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-11099.96, 2217.44, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[11070.83, 2116.56, 2021.54]}>
              <mesh geometry={nodes.Rectangle011_021_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-11167.94, 2364.44, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[11138.81, 2116.56, 1874.54]}>
              <mesh geometry={nodes.Rectangle011_022_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-11358.6, 2476.26, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[11329.47, 2116.56, 1762.72]}>
              <mesh geometry={nodes.Rectangle011_023_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-11475.21, 2655.45, -1471.94]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[11446.08, 2116.56, 1583.53]}>
              <mesh geometry={nodes.Rectangle011_024_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9864.26, 6366.89, -1921.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9835.13, 1666.83, -2127.91]}>
              <mesh geometry={nodes.Rectangle011_025_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-7316.31, 5131.47, -1921.67]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[7287.18, 1666.83, -892.49]}>
              <mesh geometry={nodes.Rectangle011_026_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9774.98, 3672.87, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9745.85, 1729.33, 566.11]}>
              <mesh geometry={nodes.Rectangle011_027_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9428.69, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9399.56, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_028_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9349.57, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9320.44, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_029_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9272.53, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9243.4, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_030_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9185.08, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9155.95, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_031_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9101.34, 6404.53, -1859.17]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9072.21, 1729.33, -2165.55]}>
              <mesh geometry={nodes.Rectangle011_032_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 4239.04, -8870.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -5281.91, -0.06]}>
              <mesh geometry={nodes.Rectangle011_033_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 4207.14, -8870.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -5281.91, 31.84]}>
              <mesh geometry={nodes.Rectangle011_034_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[1.61, 3700.21, -9620.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-30.74, -6031.91, 538.77]}>
              <mesh geometry={nodes.Rectangle011_035_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[1.61, 3609.12, -9620.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-30.74, -6031.91, 629.86]}>
              <mesh geometry={nodes.Rectangle011_036_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 817.5, -3950.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -361.52, 3421.48]}>
              <mesh geometry={nodes.Rectangle011_037_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 767.5, 1068.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 4656.91, 3471.48]}>
              <mesh geometry={nodes.Rectangle011_038_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 580, 1193.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 4781.91, 3658.98]}>
              <mesh geometry={nodes.Rectangle011_039_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 392.5, 1318.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 4906.91, 3846.48]}>
              <mesh geometry={nodes.Rectangle011_040_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 205, 1443.41]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 5031.91, 4033.98]}>
              <mesh geometry={nodes.Rectangle011_041_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-29.13, 267.5, -3845.02]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, -256.52, 3971.48]}>
              <mesh geometry={nodes.Rectangle011_042_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9346.89, 1690.36, -4389.74]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9317.76, -801.24, 2548.62]}>
              <mesh geometry={nodes.Rectangle011_043_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-9346.36, 1423.45, -1823.65]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[9317.23, 1764.85, 2815.53]}>
              <mesh geometry={nodes.Rectangle011_044_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-8358.41, 1374.04, -1823.65]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[8329.28, 1764.85, 2864.94]}>
              <mesh geometry={nodes.Rectangle011_045_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9288.63, 1690.36, -4389.74]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9317.76, -801.24, 2548.62]}>
              <mesh geometry={nodes.Rectangle011_046_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[9288.1, 1423.45, -1823.65]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-9317.23, 1764.85, 2815.53]}>
              <mesh geometry={nodes.Rectangle011_047_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[8300.15, 1374.04, -1823.65]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-8329.28, 1764.85, 2864.94]}>
              <mesh geometry={nodes.Rectangle011_048_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-26.69, 17.5, 9241.65]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-2.44, 12830.15, 4221.48]}>
              <mesh geometry={nodes.Rectangle011_049_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-26.68, 17.5, 9241.66]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-2.45, 12830.16, 4221.48]}>
              <mesh geometry={nodes.Rectangle011_050_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-26.68, 17.5, 9241.66]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[-2.45, 12830.16, 4221.48]}>
              <mesh geometry={nodes.Rectangle011_051_Colorful_light_0.geometry} material={materials.Colorful_light} />
            </group>
          </group>
          <group position={[-26.68, 5, 9241.66]} rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 21218.33, 0]}>
              <mesh geometry={nodes['NGon001_001_Stage-Black_0'].geometry} material={materials['Stage-Black']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
