/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Jaeyeon Nam (https://sketchfab.com/jaeysart)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/squid-game-pinksoldier-triangle-b8d9ee104cfa409a800186c3c887a7e0
title: Squid Game : PinkSoldier Triangle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Soldier({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/soldier.glb')
  return (
    <group ref={group} {...props} dispose={null} position={[0, -0.45, -0.2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.lambert4SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert5SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/soldier.glb')
